version: "3.8"
services: 
  postgres:
    image: 'postgres:9-alpine'

  redis:
    image: 'redis'

  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'

  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - PGHOST=postgres
      - POSTGRES_DB='postgres'
      - POSTGRES_PASSWORD='1234'
      # - POSTGRES_HOST_AUTH_METHOD="trust"
      - PGPORT=5432
      # - PGUSER=postgres
      # - PGHOST=postgres
      # - PGDATABASE='postgres'
      # - PGPASSWORD='postgress_passwprd'
      # # - POSTGRES_HOST_AUTH_METHOD="trust"
      # - PGPORT=5432

  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
  